name: codegen
on:
  - push

jobs:
  install-pspamm:
    name: install-pspamm
    runs-on: ubuntu-24.04
    steps:
      - name: apt-get
        run: |
          set -euo pipefail
          sudo apt-get update

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: checkout-pspamm
        uses: actions/checkout@v4

      - name: pip-pspamm
        run: |
          pip install .

      - name: dry-run-pspamm
        run: |
          set +e
          pspamm-generator
          retcode=$?
          set -e

          if [ $retcode -ne 2 ]; then
            echo "Unexpected exit code."
            exit 1
          fi

          echo "Success!"

  pspamm-codegen:
    name: pspamm-codegen
    runs-on: ubuntu-24.04
    needs: install-pspamm
    # include all vector lengths manually for now
    # not supported:
    # * RVV >= 1024
    # * ARM/SVE which is not a power of 2
    strategy:
      fail-fast: false
      matrix:
        arch:
          - hsw128
          - hsw256
          - knl128
          - knl256
          - knl512
          - arm128
          - arm_sve128
          - arm_sve256
          - arm_sve512
          - arm_sve1024
          - arm_sve2048
          - rvv128
          - rvv256
          - rvv512
          - rvv1024
          - lsx128
          - lsx256
    steps:
      - name: apt-get
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install g++-aarch64-linux-gnu g++-riscv64-linux-gnu g++-14-loongarch64-linux-gnu qemu-user-static

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: checkout-pspamm
        uses: actions/checkout@v4

      - name: pip-pspamm
        run: |
          pip install .

      - name: pspamm-tests
        run: |
          cd tests/
          LOCALARCH=${{matrix.arch}}
          if [[ ${LOCALARCH:0:3} == "knl" ]]; then
            ./runlocal.sh ${{matrix.arch}} norun
          else
            ./runlocal.sh ${{matrix.arch}}
          fi
